# Generated by Django 5.0.6 on 2024-05-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_review_stars_review_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rate',
            new_name='stars',
        ),
    ]
